export const OVERVIEW_TYPE = {
    MEAL: 'MEAL',
    ANYTIME: 'ANYTIME',
    QUESTION: 'QUESTION',
    MEDICATION: 'MEDICATION',
    SUPPLEMENT: 'SUPPLEMENT',
    MEASUREMENT: 'MEASUREMENT',
    ADDED_BY_PATIENT: 'ADDED_BY_PATIENT',
    PHYSICAL_ACTIVITY: 'PHYSICAL_ACTIVITY',
} as const;

export type OverviewType = typeof OVERVIEW_TYPE[keyof typeof OVERVIEW_TYPE];

export const PHASE_ITEM_STATUS = {
    DID_NOT_EAT: 'DID_NOT_EAT',
    INCOMPLETE: 'INCOMPLETE',
    PENDING: 'PENDING',
    DONE: 'DONE',
} as const;

export type PhaseItemStatus = typeof PHASE_ITEM_STATUS[keyof typeof PHASE_ITEM_STATUS];
