import react from 'eslint-plugin-react';
import reactNative from '@react-native/eslint-config';
import { defineConfig } from "eslint/config";
import globals from "globals";
import js from "@eslint/js";
import TSParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import importPlugin from "eslint-plugin-import";
export default defineConfig([
    {
        files: ['**/*.ts', '**/*.tsx'],
        languageOptions: {
            parser: TSParser,
            parserOptions: {
                ignorePatterns: ['.test.ts', '.test.tsx'],
                project: './tsconfig.json',
                ecmaVersion: 'latest',
                sourceType: 'module',
            },
            globals: {
                ...globals.es2017,
                ...globals.node,
                // ...globals.browser,
            },
        },
        plugins: {
            react,
            "@typescript-eslint": tsPlugin,
            "jsx-a11y": jsxA11yPlugin,
            "import": importPlugin,
        },
        "rules": {
            "no-bitwise": "off",
            "react/jsx-filename-extension": ["warn", { "extensions": [".js", ".jsx", ".ts", ".tsx"] }],
            "react/jsx-key": ["warn"],
            "react/forbid-prop-types": ["warn", { "forbid": ["any"] }],
            "react/prefer-stateless-function": ["warn", { "ignorePureComponents": true }],
            "react/prop-types": ["error"],
            "react/no-unused-state": ["error"],
            "react/no-unused-prop-types": ["error"],
            "react/require-default-props": ["off"],
            "react/default-props-match-prop-types": ["error"],
            "react/destructuring-assignment": ["off"],
            "react/display-name": ["off"],
            "react/jsx-indent": ["off"],
            "react/sort-comp": ["off"],
            "comma-dangle": ["off"],
            "guard-for-in": ["off"],
            "no-return-assign": ["off"],
            "prefer-destructuring": ["off"],
            "init-declarations": ["off"],
            "lines-around-comment": ["off"],
            "line-comment-position": ["off"],
            "object-curly-newline": ["off"],
            "react/jsx-wrap-multilines": ["off"],
            "react/jsx-closing-tag-location": ["off"],
            "react/jsx-indent-props": ["off"],
            "jsx-a11y/anchor-is-valid": ["error", {
                "components": ["Link"],
                "specialLink": ["to", "hrefLeft", "hrefRight"],
                "aspects": ["noHref", "invalidHref", "preferButton"]
            }],
            "import/no-unresolved": ["off"],
            // "import/no-unresolved": ["warn", { "ignore": ["../extensions/*"] }],
            "jsx-quotes": ["error", "prefer-double"],
            "quotes": ["error", "single"],
            "curly": ["warn", "all"],
            "eqeqeq": ["warn", "smart"],
            "radix": ["warn", "as-needed"],
            "semi-spacing": ["warn", { "before": false, "after": true }],
            "semi": ["error", "always"],
            "space-in-parens": ["warn", "never"],
            "arrow-parens": ["warn", "as-needed"],
            "space-before-function-paren": ["warn", "always"],
            "arrow-spacing": ["warn", { "before": true, "after": true }],
            "comma-spacing": ["warn", { "before": false, "after": true }],
            "generator-star-spacing": ["warn", { "before": true, "after": true }],
            "prefer-const": ["warn", { "ignoreReadBeforeAssign": true, "destructuring": "all" }],
            "dot-notation": ["warn", { "allowKeywords": true }],
            "comma-style": ["warn", "last"],
            "default-case": ["warn"],
            "prefer-spread": ["warn"],
            "prefer-template": ["warn"],
            "constructor-super": ["warn"],
            "yield-star-spacing": ["warn"],
            "max-depth": ["warn", { "max": 5 }],
            "max-params": ["warn", { "max": 4 }],
            "dot-location": ["warn", "property"],
            "func-call-spacing": ["warn", "never"],
            "quote-props": ["warn", "as-needed"],
            "block-spacing": ["warn", "always"],
            "key-spacing": ["warn", { "afterColon": true }],
            "operator-linebreak": ["warn", "before"],
            "space-before-blocks": ["warn", "always"],
            "rest-spread-spacing": ["warn", "never"],
            "object-curly-spacing": ["warn", "always"],
            "max-statements-per-line": ["warn", { "max": 3 }],
            "brace-style": ["warn", "1tbs", { "allowSingleLine": true }],
            "keyword-spacing": ["warn", { "before": true, "after": true }],
            "class-methods-use-this": ["warn", { "exceptMethods": ["render"] }],
            "valid-typeof": ["error", { "requireStringLiterals": true }],
            "symbol-description": ["error"],
            "eol-last": ["error", "always"],
            "new-parens": ["error"],
            "require-yield": ["error"],
            "unicode-bom": ["error"],
            "linebreak-style": ["error", "unix"],
            "yoda": ["error"],
            "array-bracket-spacing": ["error", "never"],
            "block-scoped-var": ["error"],
            "computed-property-spacing": ["error", "never"],
            "id-blacklist": ["error", "err", "cb", "callback"],
            "max-nested-callbacks": ["error", { "max": 4 }],
            "lines-between-class-members": ["error", "always"],
            "func-style": ["error", "declaration", { "allowArrowFunctions": true }],
            "camelcase": ["warn", {
                "properties": "always",
                "ignoreDestructuring": true,
                "allow": ["access_token", "refresh_token"]
            }],
            "max-len": ["error", {
                "code": 150,
                "comments": 150,
                "tabWidth": 4,
                "ignoreUrls": true,
                "ignoreStrings": true,
                "ignorePattern": "import",
                "ignoreTemplateLiterals": true,
                "ignoreTrailingComments": true
            }],
            "no-use-before-define": 0,
            "no-with": ["warn"],
            "no-new": ["error"],
            "no-undef": ["error"],
            "no-empty": ["error"],
            "no-new-func": ["error"],
            "no-unreachable": ["error"],
            "no-throw-literal": ["error"],
            "no-useless-rename": ["error"],
            "no-new-object": ["error"],
            "no-loop-func": ["error"],
            "no-multi-str": ["error"],
            "no-new-require": ["error"],
            "no-new-wrappers": ["error"],
            "no-sequences": ["error"],
            "no-useless-concat": ["error"],
            "no-var": ["error"],
            "no-proto": ["error"],
            "no-useless-call": ["error"],
            "no-useless-constructor": ["error"],
            "no-duplicate-imports": ["error", { "includeExports": true }],
            "no-underscore-dangle": ["error", { "allow": ["_object", "_number", "__REDUX_DEVTOOLS_EXTENSION_COMPOSE__"] }],
            "no-mixed-operators": ["error", { "groups": [["&&", "||"]] }],
            "import/no-cycle": ["error", { "maxDepth": 1 }],
            "no-spaced-func": ["error"],
            "no-unused-labels": ["error"],
            "no-floating-decimal": ["error"],
            "no-implied-eval": ["error"],
            "no-lone-blocks": ["error"],
            "no-iterator": ["error"],
            "no-labels": ["error"],
            "no-restricted-imports": ["error", {
                "paths": ["import1", "import2"],
                "patterns": ["import1/private/*", "import2/*", "!import2/good"]
            }],
            "no-console": ["warn", { "allow": ["error", "warn", "info"] }],
            "no-fallthrough": ["warn", { "commentPattern": "no-break" }],
            "no-extend-native": ["warn", { "exceptions": ["Error", "Array"] }],
            "no-multiple-empty-lines": ["warn", { "max": 2, "maxEOF": 1, "maxBOF": 1 }],
            "no-restricted-globals": ["warn", { "name": "event", "message": "Use local parameter instead." }],
            "no-undef-init": ["warn"],
            "no-useless-computed-key": ["warn"],
            "no-unneeded-ternary": ["warn", { "defaultAssignment": true }],
            "no-unsafe-negation": ["warn"],
            "no-unused-vars": ["warn", { "vars": "local", "args": "none", "ignoreRestSiblings": true }],
            "no-tabs": ["warn"],
            "global-require": ["warn"],
            "no-else-return": ["warn"],
            "no-multi-assign": ["warn"],
            "no-useless-escape": ["warn"],
            "indent": ["warn", 4, { "SwitchCase": 1 }],
            "no-confusing-arrow": ["warn", { "allowParens": true }],
            "no-multi-spaces": ["warn", { "ignoreEOLComments": true }],
            "no-trailing-spaces": ["warn", { "skipBlankLines": true }],
            "one-var": ["off"],
            "no-shadow": ["off"],
            "import/order": ["off"],
            "consistent-return": ["off"],
            "no-param-reassign": ["off"],
            "no-nested-ternary": ["off"],
            "no-unused-expressions": ["off"],
            "import/no-named-as-default": ["off"],
            "prefer-promise-reject-errors": ["off"],
            "react/no-access-state-in-setstate": ["off"],
            "no-plusplus": ["off", { "allowForLoopAfterthoughts": true }],
            "valid-jsdoc": ["off", {
                "requireReturn": false,
                "requireReturnType": true,
                "requireParamDescription": true,
                "requireReturnDescription": false,
                "preferType": {
                    "boolean": "Boolean",
                    "number": "Number",
                    "object": "Object",
                    "string": "String"
                }
            }],
            "require-jsdoc": ["off", {
                "require": {
                    "FunctionDeclaration": true,
                    "MethodDefinition": true,
                    "ClassDeclaration": true,
                    "ArrowFunctionExpression": true,
                    "FunctionExpression": true
                }
            }]
        }
    },
    {
        files: ["**/*.js"], languageOptions: {
            globals: globals.es2017
        }
    },
    { files: ["**/*.js"], plugins: { js }, extends: ["js/recommended"] },
    {
        files: ['*.ts', '*.tsx'],
        rules: {
            '@typescript-eslint/no-unused-vars': 'warn',
            '@typescript-eslint/explicit-module-boundary-types': 'off'
        }
    }
]);
