
auth.token=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

defaults.org=intelliceed-gs
defaults.project=healthene-mobile

defaults.url=https://sentry.io/
