// outsource dependencies
import Video from 'react-native-video';
import React, { useState } from 'react';
import { useNavigation } from '@react-navigation/native';
import Icon from '@react-native-vector-icons/material-icons';
import { ReactNativeBlobUtilStat } from 'react-native-blob-util';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Dimensions, Image, Platform, Pressable, StyleSheet, View } from 'react-native';

// local dependencies
import Text from 'components/Text.tsx';
import { ROUTES } from 'constants/routes.ts';
import { useTheme } from 'hooks/useTheme.ts';
import { OFFSET } from 'constants/offset.ts';
import { Button } from 'components/Button.tsx';
import { Attachment } from 'types/messenger.ts';
import AudioPlayer from 'components/AudioPlayer.tsx';
import LoadingOverlay from 'components/LoadingOverlay.tsx';
import { RootStackParamList } from 'services/navigation';
import { handleCapture } from 'utils/attachment/mediaCapture.ts';

export interface CapturedMedia {
    path: string;
    duration?: number;
    type: 'photo' | 'video';
    // Generated first-frame image for Android video previews — see Camera/index.tsx
    // (Honor MagicOS / ExoPlayer crash workaround).
    thumbnailPath?: string;
}

interface RecordPreviewProps {
    onRetake: () => void;
    recordType: 'camera' | 'audio'
    onCapture: (item: Attachment) => void;
    file: CapturedMedia | ReactNativeBlobUtilStat | null,
}

export const RecordPreview = ({ file, onRetake, onCapture, recordType }: RecordPreviewProps) => {
    const theme = useTheme();
    const navigation = useNavigation<NativeStackNavigationProp<RootStackParamList>>();
    const isVideo = Boolean(file && 'type' in file && file.type === 'video');
    const [preloader, setPreloader] = useState<boolean>(false);
    const androidThumbnail = Platform.OS === 'android' && file && 'thumbnailPath' in file
        ? file.thumbnailPath
        : undefined;

    const getCaptureType = () => {
        if (isVideo) { return 'video'; }
        if (recordType === 'audio') { return 'audio'; }
        return 'image';
    };

    const onPressSave = async () => {
        if (!file) { return; }
        const captureType = getCaptureType();
        const attachment = await handleCapture({
            file,
            captureType,
            setPreloader
        });

        if (attachment) {
            onCapture(attachment);
        }
        onRetake();
    };

    // Android: open the recording in the in-app WebView viewer (Chrome media stack,
    // no ExoPlayer codec init, controls visible, stays in the messenger flow).
    const openInViewer = () => {
        if (!file?.path) { return; }
        navigation.navigate(ROUTES.MESSENGER_ATTACHMENT_VIEWER, {
            uri: `file://${file.path}`,
            mimeType: 'video/mp4',
            title: 'Preview',
        });
    };

    return <>
        <LoadingOverlay init={preloader} />
        <View style={styles.container}>
            <Text style={styles.title} textAlign="center" variant="h2">Review your capture</Text>
            {recordType === 'camera' && file?.path
                ? <View style={[styles.wrapper, styles.height]}>
                    {isVideo
                        ? Platform.OS === 'android'
                            // Android: show the first-frame thumbnail generated by
                            // react-native-create-thumbnail (Camera/index.tsx). ExoPlayer
                            // crashes on this OEM's media stack when mounted, so we keep
                            // the preview to a plain <Image>. Falls back to a film icon
                            // placeholder if thumbnail generation failed for some reason.
                            ? androidThumbnail
                                ? <Pressable onPress={openInViewer} style={styles.media}>
                                    <Image
                                        source={{ uri: `file://${androidThumbnail}` }}
                                        style={styles.media}
                                        resizeMode="cover"
                                    />
                                    <View style={styles.playOverlay}>
                                        <Icon name="play-circle-fill" size={80} color={theme.colors.white} />
                                    </View>
                                    {file && 'duration' in file && typeof file.duration === 'number'
                                        ? <View style={styles.durationBadge}>
                                            <Text color={theme.colors.white} variant="caption">
                                                {file.duration}s
                                            </Text>
                                        </View>
                                        : null}
                                </Pressable>
                                : <View style={[styles.media, styles.videoPlaceholder, { backgroundColor: theme.colors.lighterGrey }]}>
                                    <Icon name="movie" size={96} color={theme.colors.darkGrey} />
                                    <Text
                                        variant="h3"
                                        textAlign="center"
                                        color={theme.colors.darkGrey}
                                        style={styles.placeholderLabel}
                                    >
                                        Video recorded
                                        {file && 'duration' in file && typeof file.duration === 'number'
                                            ? ` · ${file.duration}s`
                                            : ''}
                                    </Text>
                                </View>
                            : <Video paused controls source={{ uri: `file://${file?.path}` }} style={styles.media}/>
                        : <Image source={{ uri: `file://${file?.path}` }} style={styles.media}/>
                    }
                </View>
                : <View style={[styles.audioWrapper, styles.height]}>
                    <Icon
                        size={168}
                        style={styles.icon}
                        name="multitrack-audio"
                        color={theme.colors.darkGrey}
                    />
                    <View style={styles.marginAuto}>
                        <AudioPlayer file={file?.path} />
                    </View>
                </View>
            }
            <View style={[styles.actions, styles.wrapper]}>
                <Button variant="outline" style={styles.flex} title="Retake" onPress={() => onRetake()} />
                <Button variant="outline" style={styles.flex} title="Ready" onPress={() => onPressSave()} />
            </View>
        </View>
    </>;
};

export default RecordPreview;

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
    },
    title: {
        marginVertical: OFFSET.VERTICAL,
    },
    wrapper: {
        width: Dimensions.get('window').width * 0.8,
    },
    height: {
        ...Platform.select({
            ios: { height: Dimensions.get('window').width * 0.8 * (4 / 3) },
            android: { height: Dimensions.get('window').width * 0.8 * (5 / 3) },
        })
    },
    audioWrapper: {
        width: '100%',
        paddingHorizontal: OFFSET.HORIZONTAL,
    },
    media: {
        width: '100%',
        height: '100%',
    },
    videoPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 8,
    },
    placeholderLabel: {
        marginTop: OFFSET.POINT,
    },
    durationBadge: {
        position: 'absolute',
        right: OFFSET.POINT,
        bottom: OFFSET.POINT,
        paddingVertical: OFFSET.POINT / 2,
        paddingHorizontal: OFFSET.POINT,
        borderRadius: 4,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    playOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    actions: {
        flexDirection: 'row',
        justifyContent: 'center',
        width: '100%',
        marginVertical: OFFSET.VERTICAL,
        gap: OFFSET.POINT * 4
    },
    icon: {
        alignSelf: 'center',
    },
    marginAuto: {
        marginTop: 'auto'
    },
    flex: {
        flex: 1
    }
});
